#*******************************************************************************************
#example (Fresher)
numbers = [0,1,2,3,4,5,6,7,8,9,10]   # This line initializes a list called numbers containing integers from 0 to 10.
event_number = []                    # This line initializes an empty list called even_numbers to store even numbers.
for i in numbers:                    # This line iterates through each element i in the list numbers.
    if i%2 ==0:                      # This line checks if the current number i is even by using the modulo operator % to 
                                     #check if it is divisible by 2 with no remainder.
        event_number.append(i)       # If the number i is even, it is appended to the even_numbers list.
print(event_number)
#display:  [0,2,4,6,8,10]   


#*******************************************************************************************
#example (Intermittent)
event_numbers = [x for x in range(11) if x%2==0]      
print(event_numbers)
#display:  [0,2,4,6,8,10]

#explanations
# 1.  [x for x in range(11) if x % 2 == 0]: This is a list comprehension, a concise way to create lists in Python.
# 2.  range(11):  This creates an iterable containing numbers from 0 to 10 (11 is exclusive)
# 3.  if x % 2 == 0:   This is a conditional expression that checks if the number x is even (i.e., divisible by 2 with no remainder).  
# 4.  For each value x in the range from 0 to 10, the condition x % 2 == 0 is checked.
# 4.1 If the condition is True, x is included in the list.
# 4.2 The result is a list of even numbers from 0 to 10.
# 5. print(event_numbers): This line prints the list of even numbers generated by the list comprehension.

#*******************************************************************************************
#example (Expert)
print(list(range(0,11,2)))
#display:  [0,2,4,6,8,10]

#explanation
# 1. range(0, 11, 2):   This creates a range object that generates numbers starting from 0 (inclusive), up to 11 (exclusive), in steps of 2.
# 2. list(range(0, 11, 2)): 
#       The range object is converted into a list using the list() constructor.
#       This creates a list containing the numbers generated by the range object.
# print(...):   This line prints the resulting list.

# This is the list of even numbers from 0 to 10, generated using the range() function with a step of 2, and then converted to a list.